name: Build StateGo

on:
  workflow_dispatch:
  push:
    branches: [ "master", "main", "tougou_conv" ]
  pull_request:
    branches: [ "master", "main", "tougou_conv" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Setup NuGet
      uses: nuget/setup-nuget@v1
      with:
        nuget-version: '5.x'



    - name: Determine MSBuild Path and Run
      shell: cmd
      run: |
        for /f "usebackq tokens=*" %%i in (`vswhere -latest -requires Microsoft.Component.MSBuild -find MSBuild\**\Bin\MSBuild.exe`) do (
          set MSBUILD17=%%i
        )
        set NUGET=nuget
        .\BuildAuto.bat

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: StateGo-Release
        path: m1/StateViewer/StateViewer/bin/Release
